spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 671879906222-b68u8vrd388n0ch2euquoeerrsvk1uvi.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  jpa:
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
    # 전송 쿼리 확인
    show-sql : true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url : jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

jwt:
  issuer : ahtnwl1004@gmail.com
  secret_key: study-springboot

# client-id: 671879906222-b68u8vrd388n0ch2euquoeerrsvk1uvi.apps.googleusercontent.com

# secret-key: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
